import Head from "next/head";
import Link from "next/link";
import Header from "../components/Header";
import styles from "../styles/Home.module.css";
import { useRouter } from "next/router";

interface Props {
  locations: Props[];
  id: number;
  name: string;
  type: string;
}

const Locations = ({ locations }: Props) => {
  const router = useRouter();
  const page = Number(router.query.page) || 1;

  return (
    <div>
      <Head>
        <title>Rick and Morty</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className={styles.container}>
        {locations.map((location) => (
          <Link href={`/location/${location.id}`} key={location.id}>
            <a>
              <section className={styles.location__card}>
                <div>
                  <h3 className={styles.location__card__name}>
                    Location Name: {location.name}
                  </h3>
                  <span className={styles.location__card__type}>
                    Type: {location.type}
                  </span>
                </div>
              </section>
            </a>
          </Link>
        ))}
      </main>
      <div className={styles.page__buttons}>
      {page <= 1 ? null : (
          <Link href={`/${page - 1}`}>
            <button>Previous</button>
          </Link>
        )}
        {page >= 7 ? null : (
          <Link href={`/${page + 1}`}>
            <button>Next</button>
          </Link>
        )}
      </div>
    </div>
  );
};

export default Locations;
